name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      
      - name: Install frontend dependencies
        run: |
          cd client
          npm ci
      
      - name: Build frontend
        run: |
          cd client
          npm run build
      
      - name: Copy frontend build to Go directory
        run: |
          mkdir -p static
          cp -r client/dist/* static/
      
      - name: Set version variables
        id: vars
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
      
      - name: Build Binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -ldflags "-X 'github.com/Facets-cloud/kube-dash/cmd/server.Version=${VERSION}' -X 'github.com/Facets-cloud/kube-dash/cmd/server.Commit=${COMMIT}' -X 'github.com/Facets-cloud/kube-dash/cmd/server.BuildDate=${DATE}'" -o kube-dash-linux-amd64 ./cmd/server
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X 'github.com/Facets-cloud/kube-dash/cmd/server.Version=${VERSION}' -X 'github.com/Facets-cloud/kube-dash/cmd/server.Commit=${COMMIT}' -X 'github.com/Facets-cloud/kube-dash/cmd/server.BuildDate=${DATE}'" -o kube-dash-darwin-amd64 ./cmd/server
          GOOS=darwin GOARCH=arm64 go build -ldflags "-X 'github.com/Facets-cloud/kube-dash/cmd/server.Version=${VERSION}' -X 'github.com/Facets-cloud/kube-dash/cmd/server.Commit=${COMMIT}' -X 'github.com/Facets-cloud/kube-dash/cmd/server.BuildDate=${DATE}'" -o kube-dash-darwin-arm64 ./cmd/server
          GOOS=windows GOARCH=amd64 go build -ldflags "-X 'github.com/Facets-cloud/kube-dash/cmd/server.Version=${VERSION}' -X 'github.com/Facets-cloud/kube-dash/cmd/server.Commit=${COMMIT}' -X 'github.com/Facets-cloud/kube-dash/cmd/server.BuildDate=${DATE}'" -o kube-dash-windows-amd64.exe ./cmd/server
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kube-dash-linux-amd64
            kube-dash-darwin-amd64
            kube-dash-darwin-arm64
            kube-dash-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 